### ISSUE TITLE
2 decimal place values for future sales?

### ISSUE THREAD

**Issue by a1ch3mist** [wligithub/tax-tool#12]
I used your sheet for my post-merger 2023 sales. It was helpful to see the total cost basis in the AVGO lot, but I noticed that etrade reported the sales to 2-decimals, whereas your sheet has 3-decimals, resulting in some differences in rounding of values.

I don't know if other brokerages will report 3-decimal, but for etrade, it is 2-decimal to match up with the 1099 sales.

**Comment by wligithub** [comment]
I heard Fidelity uses 3-decimals. Could you please give an example as what difference does it make with 2 decimals verses 3 decimals?

**Comment by wligithub** [comment]
Close due to no response.

>
