### ISSUE TITLE
How to get cost basis for AVGO shares sold post-merger?

### ISSUE THREAD

**Issue by astorije** [wligithub/tax-tool#15]
Hi there,

First of all, thank you so so much for this tool, it was immensely helpful to get the correct information for shares held through the merger.

I have sold shares after the merger (both in 2023 and 2024) on multiple occasions. Let's say I had 5 RSU lots regarding the merger itself, when I run the script, it outputs the following lines in the terminal:

```
Sold AVGO after merge date, row id=6, share=0.657
Sold AVGO after merge date, row id=7, share=1.049
Sold AVGO after merge date, row id=8, share=1.308
...
```

However, neither the CSV and TXT output files contain those `row id`s, as they both stop at `row id` of `5`. The G&L spreadsheet only contains `--` for `Adjusted Cost Basis`.

How does one compute the correct cost basis (to input into Turbotax)? Thanks!

**Comment by wligithub** [comment]
"row id" in csv/txt file corresponds to the ID of the corresponding row from the Gain&Loss input file. This correlation allows for easy matching between computed lots from the output and reported lots from the input. 

Tax tool computes avgo cost base for each merged vmw row. To find the cost base of sold avgo share, please locate the corresponding vmw row from which converted shares are sold, you can use "Date Acquired" and "Qty." as hint to find corresponding vmw row. From that row, look for "total avgo cost base" and "per share avgo cost base". If you sold all converted avgo shares from that vmw lot, use "total avgo cost base". If you only sold say 1.2 share from that row, use "per share avgo cost base" * 1.2.

**Comment by astorije** [comment]
> Tax tool computes avgo cost base for each merged vmw row. To find the cost base of sold avgo share, please locate the corresponding vmw row from which converted shares are sold, you can use "Date Acquired" and "Qty." as hint to find corresponding vmw row. From that row, look for "total avgo cost base" and "per share avgo cost base". If you sold all converted avgo shares from that vmw lot, use "total avgo cost base". If you only sold say 1.2 share from that row, use "per share avgo cost base" * 1.2.

To future me and others finding this, there was a 10-for-1 stock split on 15 July 2024. So if I understand correctly, since tax tool computes pre-stock split, if the lot was sold after the split, "per share avgo cost base" should be divided by 10 to get the correct cost basis.
@wligithub @weili-broadcom could you fact check me? 🙏

**Comment by weili-broadcom** [comment]
Correct. For example, before split, you have 10 avgo shares with cost base of $90 per share. So total cost base is 10*90=$900. After split, you have 100 avgo shares with cost base of $9 per share. The total cost base is 100*9=$900. The total cost base remain the same, the per share cost base is divided by 10 after split.

**Comment by astorije** [comment]
Amazing, thank you!
