### ISSUE TITLE
cannot open with open(VMW_PRICE_FILE) as csvfile

### ISSUE THREAD

**Issue by ramnathkalakota** [wligithub/tax-tool#2]
I am trying to run the script against my data and I am getting below error

rkalakota@rkalakotaGMD6R forPythonScript % python3 tax.py GainsAndLossesExpandedFromEtrade.csv output -c 78 -s 21 -f
Output files: output.txt, output.csv
Traceback (most recent call last):
  File "tax.py", line 215, in <module>
    main()
  File "tax.py", line 35, in main
    tax_lot.load_historical_price()
  File "/Users/rkalakota/Downloads/2024taxes/newConsolidatedDocs/forPythonScript/tax_lot.py", line 67, in load_historical_price
    with open(VMW_PRICE_FILE) as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'data/vmw-historical-price.csv'
rkalakota@rkalakotaGMD6R forPythonScript

**Comment by ramnathkalakota** [comment]
Had to download the entire folder.

**Comment by spamguy** [comment]
Facing the same problem, but the file and its directory most definitely exist. Running Ubuntu within Windows 11.

**Comment by wligithub** [comment]
Need to cd into that dir to run.

**Comment by spamguy** [comment]
Thank you, I was working from my tax document dir. Shows how often I use Python. :)
