### ISSUE TITLE
Multiple Fractional Lot Issue?

### ISSUE THREAD

**Issue by tcduong** [wligithub/tax-tool#4]
Hi,  

I was validating my data and using your script to double check. I think there is a problem with fractional lot from the vmw exchange  but sold at different date. 

I have a vmw lot that was broken into multiple avgo fractional share lots.

Example:
VMW         Date ACQ.        Date Sold
9.0             02/01/22          11/24/23

AVGO        Date ACQ.        Date Sold
1.183         02/01/22          12/07/23
0.001         02/01/22          12/14/23          

The output only show 1 lot above and the first value from the lot. The  other  fractional lot seems to be ignored. Lot with 1:1 that sold the  same date do not seem to have this issue.

Thank you so much for putting this together to help us!

**Comment by alvinhau** [comment]
I have a similar issue - I only have one fractional row, but it was being ignored.  Originally, the Date Acquired was wrong 1/1/1970 - but it still got ignored after I fixed the date...  Thanks!!!

**Comment by tcduong** [comment]
Interesting. I don't have that data issue. I just read the readme again and notice that this support before and day of merger...  For cases like mine, sold after the merger, part of the code just print out the rows that needs to be handle manually.... I'm not sure if I did the tax for these kind of lots correctly.

Sold AVGO after merge date, row id=xxx, share=xxx

**Comment by tcduong** [comment]
Ok. I don't think there is an issue here - my bad. I misunderstood the usage of the fractional share. I read Gary's post over slack and understand it just t reduce the cost basis of that lot. This script output the right lot.

Because my tax software has all these fractional lots, i thought i had to adjust the cost basis for each fractional lot...

Thanks again for the useful script.

**Comment by alvinhau** [comment]
Apparently, your issue is different from mine - I'll need to open a new issue...

**Comment by wligithub** [comment]
For avgo share sold after merge, you can find the vmw lot from which the avgo shares are converted from, then use computed avgo cost base of that lot in output file to report your sold avgo cost base.
