### ISSUE TITLE
Is this the right way to think about the cost basis (it isn't zero) for the cash component?

### ISSUE THREAD

**Issue by ps3btc** [wligithub/tax-tool#9]
Is this the right way to think about the cost basis (it isn't zero) for the cash component?

https://docs.google.com/spreadsheets/d/19MNip_tRXk7Z7qucGdSIJf4V79HwH3_L8vILMAVG7XQ/edit#gid=0

When I run your script I get a cost basis of $0 for the cash component but in the spreadsheet above I estimate it in Row 11? Does that look right? If it doesn't why not? Thanks in advance!!

**Comment by wligithub** [comment]
You spent $9000 to acquire 100 share of vmw. Per your calc, you new cost base becomes 4311 + 51032 = $55343, which is not right. After merge,  you received $6826 cash, for which you need to pay capital gain tax on it. Then, your cost base remains at $9000 for converted avgo shares.
Please refer to README, section "[Q] My lot cost base is still 0, is this expected?" for detailed explanation.
